Name:           cpanspec
Version:        2.0_1
Release:        1%{?dist}
Epoch:          4
Summary:        cpanspec Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/cpanspec/
Source0:        http://www.cpan.org/modules/by-module/cpanspec/cpanspec-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Archive::Tar)
BuildRequires:  perl(Archive::Zip)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(IO::Uncompress::Bunzip2)
BuildRequires:  perl(IPC::Run)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::CoreList)
BuildRequires:  perl(Module::ExtractUse) >= 0.33
BuildRequires:  perl(Parse::CPAN::Packages)
BuildRequires:  perl(Perl::Version) >= 1.013
BuildRequires:  perl(Pod::Simple::TextContent)
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::Autoformat)
BuildRequires:  perl(YAML)
Requires:       perl(Archive::Tar)
Requires:       perl(Archive::Zip)
Requires:       perl(Getopt::Long)
Requires:       perl(IO::Uncompress::Bunzip2)
Requires:       perl(IPC::Run)
Requires:       perl(LWP::UserAgent)
Requires:       perl(Module::CoreList)
Requires:       perl(Module::ExtractUse) >= 0.33
Requires:       perl(Parse::CPAN::Packages)
Requires:       perl(Perl::Version) >= 1.013
Requires:       perl(Pod::Simple::TextContent)
Requires:       perl(Pod::Usage)
Requires:       perl(Text::Autoformat)
Requires:       perl(YAML)
Provides:       perl(cpanspec) = 4:2.0_1
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
{{{         docker images        docker rmi $IDs        docker volume
ls        docker volume inspect cpanspec-test        docker volume ls
-q | xargs docker volume inspect        docker volume ls -q | xargs
docker volume rm }}}

%prep
%setup -q

%build
%{__perl} Build.PL --installdirs=vendor 
%{__perl} -p -i -e 's/^Module::Build->VERSION/#Module::Build->VERSION/g' Build

./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING README.md TODO
%{_mandir}/*
%{_bindir}/*
%{_datadir}/*

%changelog
* Tue Nov 14 2017 "Jeff Fearn <jfearn@redhat.com>" 2.0_1-1
- Specfile autogenerated by cpanspec 2.0_1.

